### ISSUE TITLE
bulk update alerts

### ISSUE THREAD

**Issue by adamstauffer** [controlscanmdr/cyphon#149]
This is a feature request for a workflow to bulk update alert properties, such as

* status
* level
* assignee
* outcome w/ analysis
* adding comments
* actions

ideally a single form that would apply all properties to selected alerts in cyclops. admin panel is a workaround for now but would like something for regular users too

**Comment by chasepbrewer** [comment]
This has been in our feature backlog for a while. I'm currently implementing another feature, but after that's done I can look into moving the bulk update feature up in priority.

**Comment by cruscio** [comment]
Came to make this same request, found the existing enhancement, wanted to add my voice as interested in this feature.

**Comment by cruscio** [comment]
@chasepbrewer if you have an outline I'd be interested in contributing toward this enhancement.

**Comment by chasepbrewer** [comment]
We don't yet have an outline for Cyphon contribution, but we do have [documentation for Cyphon](http://cyphon.readthedocs.io/en/latest/contributing/contributing.html). The contributing section only covers how to write documentation for created methods, classes, etc. It's built with Django, so if you've worked with a project that uses Django or if you just brush up on their [documentation](https://docs.djangoproject.com/en/1.11/) you should be fine.

We also don't have an outline for Cyclops contribution, and unfortunately the current documentation for it is limited and outdated. I'm working on standardizing architecture decisions and folder structures I've adapted in certain parts of the project as it's grown in the past year. I've been focused on implementing search the past few months and haven't had much time to focus on standardization, documentation, or guidelines. I'll see if it can be made more of a priority, since this feature would mostly be a [Cyclops](https://github.com/dunbarcyber/cyclops) change. I'm the main developer for that repository, so please direct any questions you have about developing on it towards me.
