### ISSUE TITLE
Can I use Cyphon for Incident Management only?

### ISSUE THREAD

**Issue by Blason** [controlscanmdr/cyphon#455]
Hi Team,

I have other ELK based software which is being used for Log Analysis and management and kind of SIEM solution. Would like to know if we can use Cyphon for Incident management and Response purpose only?

**Comment by lhadjchikh** [comment]
Yes, you can just use it to manage and respond to alerts from your SIEM.

**Comment by chasepbrewer** [comment]
It should be documented [here](http://cyphon.readthedocs.io/en/latest/tutorials/logstash-tutorial.html?highlight=logstash#). You forward logs from Logstash to both your Elasticsearch cluster and Cyphon. This way, Cyphon only handles creating and storing alerts and doesn't handle storing the raw data.

**Comment by Blason** [comment]
Thanks for it. Let me have a look at it.

**Comment by santi10** [comment]
Blason,

Do you set your solution?? Do you give to start it??

Thanks

**Comment by Blason** [comment]
I am still not sure how this would fly. I mean since I already have much
powerful server for correlation which is on 10 core/64GB RAM/10TB HD,
really will not get another same server for storing the logs.

And does that mean Cyphon will not store the logs and and whatever logs are
pumping in will just be used to creating alerts and then logs will not be
stored and dropped?

**Comment by chasepbrewer** [comment]
If you forward your logs from Logstash into both Elasticsearch and Cyphon simultaneously, then Elasticsearch will handle storing the log and Cyphon will handle creating an alert from that log. If Cyphon decides that it needs to create an alert based on that log, it stores that log into it's own PostgreSQL database as a JSON object along with information like the alert level, status, and parsing rules that set that alert off. Elasticsearch would be storing the original log and Cyphon would be storing a copy of it along with some metadata. Your logstash config would look something like this:

```
output {
  elasticsearch {
    hosts => ["elasticsearch"]
    index => "cyphon-%{+YYYY-MM-dd}"
    document_id => "%{@uuid}"
  }

  rabbitmq {
    host => "rabbit"
    port => 5672
    exchange => "cyphon"
    exchange_type => "direct"
    key => "logstash"
    user => "guest"
    password => "guest"
    vhost => "cyphon"
    durable => true
    persistent => true
  }
}
```

We use this method at work because we're ingesting and storing terabytes of data a week across a distributed system and Cyphon became a bottleneck if we sat it between Logstash and Elasticsearch. Our database that stores the alerts and configuration data is only a few gigabytes. The footprint of Cyphon on your machine should be tiny as long as you're not alerting on every single piece of data going through the system. One guy that was trying out the tool alerted on everything and quickly had a database of a million alerts.

Take a look at our [cyphondock](https://github.com/dunbarcyber/cyphondock) repository. You could modify your own docker-compose file based on the one there to only include the cyphon, rabbit, postrgres, and nginx services and it should run. I'll see if I can put one together today since I'm looking at a post @santi10 did that is sorta related dunbarcyber/cyphon#501.

**Comment by Blason** [comment]
This is interesting; let me prepare the diagram whatever I understood and
then let me know if the assumptions are right?

**Comment by Blason** [comment]
Hi there,

As discussed please see the enclosed PPT image which I feel the positioning
of Cyphon? Please correct me if I am wrong?

In this case then Alerts are coming to Centralized logstash instance and
then are being sent to EK instance. So the logstash instance would again
send one more copy to Cyphon? and analysts then look at the cyphon and then
respond?

Also in that case if you recollect my EK server is pretty powerful in terms
of resources. Do I need to have same server for Cyphon as well?or even it
would fly with Mediocre configuration?

**Comment by Blason** [comment]
Oops forgot to attach the attachment.

**Comment by fatalglitch** [comment]
I can't see any attachment, but I'll try to walk through the process. Please make sure to read through this completely before you make ANY changes to your current environment.

Assumptions:
1) You have an existing ELK stack in place, with logstash receiving all the log data from disparate systems, parsing the data, and delivering to Elasticsearch for ingestion/storage.
2) Logstash is parsing the data, and applying different datasets to different indices

Solution:
--Taking the example of a log set that is parsed and stored in an index named "mylogdata-2018-04-13"

You would configure Cyphon with a bottle that defines the specific fields you care to show up in the details for the alerts. The data types of the fields should match the data types of the existing data, this is important.

Once the bottle is created, create a container that uses that bottle, and, at a minimum, set Title and DateTime to fields you have defined, along with any other values.

Once the container is defined, you create a warehouse named mylogdata in cyphon with the backend as elasticsearch.

After the warehouse is created, you create a collection with the name "mylogdata" and the warehouise set to "elasticsearch.mylogdata"

Now, create a distillery "MyLogData" with collection as "elasticsearch.mylogdata.mylogdata" and choose the container you created earlier. Check the box "Is shell" since cyphon is not storing the data, logstash is storing it to elasticsearch.

At this point, Cyphon is aware of the data, and you can now continue to setup Watchdogs, Monitors, and etc. to generate the alerts. To alert off this data, you need to setup a data sieve made from data rules defined in the Admin->Sifting Data->JSON Data-> section of the admin interface.

Once the data rules, sieves, and watchdog is setup, the method to send alerts into Cyphon is by sending the data from logstash to rabbitmq. Below is an example output configuration for logstash.

```output {

  if [type] in ["mylogdata"] {
      rabbitmq {
          host => "rabbit"
          port => 5672
          exchange => "cyphon"
          exchange_type => "direct"
          key => "watchdogs"
          user => "guest"
          password => "guest"
          vhost => "cyphon"
          durable => true
          persistent => true
      }
  }

}```

**Comment by fatalglitch** [comment]
Please keep in mind, Cyphon is designed for Elasticsearch 5.X, and is not yet certified for 6.X

The single most important breaking change in 6.X for Cyphon is the removal of multiple doctypes in an index. Cyphon sets a template into elasticsearch based on each distillery. Ie. a distillery named "elasticsearch.mylogdata.mylogdata" will create an index template for an index_pattern of "mylogdata-*-*-*" with a doctype of "mylogdata". An example of this template it creates is below:

```
  "dns.suricata": {
    "order": 0,
    "index_patterns": [
      "dns-*-*-*"
    ],
    "settings": {
      "index": {
        "number_of_shards": "1",
        "mapping": {
          "ignore_malformed": "true"
        }
      }
    },
    "mappings": {
      "suricata": {
        "properties": {
          "alert": {
            "properties": {
              "action": {
                "type": "keyword"
              },
              "category": {
                "type": "keyword"
              },
              "gid": {
                "type": "integer"
              },
              "rev": {
                "type": "integer"
              },
              "severity": {
                "type": "integer"
              },
              "signature": {
                "type": "keyword"
              },
              "signature_id": {
                "type": "float"
              }
            }
          }
....
} ```

**Comment by Blason** [comment]
Thanks for the detail explanation and I really appreciate. I had sent the
attachment in my earlier mail and here is again if you didnt get it.  Yes I
am relying heavily on BRO, Suricata and many more components. In fact its
almost a Security Onion distro with modifications here and there.

**Comment by ananth07reddy** [comment]
Hi, 

I am very much interested in this solution. @Blason  Have you already set it up with ELK stack? In my case, I have EFK (Elasticsearch, Fluentd, and Kibana ) stack for the log management and would like to integrate Cyphon for the incident management and response. I am not sure how to test it first. Should I have logstash to work work with cyphon?

Best regards,
Anantha

**Comment by Blason** [comment]
Nope, I didn't give a try but would definitely want to. let me know if you
are succeeded with your setup?

**Comment by sathishkgit** [comment]
@fatalglitch Does cyphon work with elasticsearch 7.x? do you have an cyphons updated mapper.py for elasticsearch 7.x support?

**Comment by fatalglitch** [comment]
We are working on ES 6 and ES 7 official support for Cyphon Open Source.
